### ISSUE TITLE
bug: availd.service: Failed with result 'signal'

### ISSUE THREAD

**Issue by vinatechpro** [availproject/avail#441]
# Bug Report

Availd Service auto kill process when sync node.

## Description

Avail auto kill & restart ~ 12m-15m once.
Log:
```
Feb 25 23:28:14 vmi1676799 systemd[1]: availd.service: Main process exited, code=killed, status=9/KILL
Feb 25 23:28:14 vmi1676799 systemd[1]: availd.service: Failed with result 'signal'.
```
image:
![1](https://github.com/availproject/avail/assets/149946061/0921da1c-b679-46ca-a434-0bc716fdfc6d)
![2](https://github.com/availproject/avail/assets/149946061/3e22772a-6f3b-4f9f-abb0-e262084317e3)

## Steps to Reproduce

1. I setup node & sync data full db: https://github.com/availproject/avail/releases/tag/v1.10.0.0
2. Exce: `/root/avail/target/release/data-avail -d /root/avail/output --chain goldberg --name LD-Fullnode --unsafe-da-sync`
4. Service start normal and loop kill process ~ 12m - 15m / once

**Comment by pantpa99** [comment]
Try reinstall node

remove availd.service
```
systemctl stop availd.service && systemctl disable availd.service && rm /etc/systemd/system/availd.service && rm /etc/systemd/system/availd.service && rm /usr/lib/systemd/system/availd.service && rm /usr/lib/systemd/system/availd.service && systemctl daemon-reload && systemctl reset-failed
```

delete db & network
`cd ~ && rm -r /root/avail/output/chains/avail_goldberg_testnet/db/* && rm -r /root/avail/output/chains/avail_goldberg_testnet/network/*`

download snapshot
`sudo apt-get -y install lz4 && curl -o - -L http://snapshots.staking4all.org/snapshots/avail/latest/avail.tar.lz4 | lz4 -c -d - | tar -x -C /root/avail/output/chains/avail_goldberg_testnet/`

reload availd.service
`sudo systemctl daemon-reload && sudo systemctl enable availd.service && sudo systemctl start avail.service && systemctl status availd.service`

**Comment by vinatechpro** [comment]
The problem is still not resolved, bro. I tried reinstall but it still didn't work.

**Comment by SakshiJain01** [comment]
It is due to the "The system cannot write the downloaded file to the specified location (/output/data/chains/avail_goldberg_testnet)."

This error "Killed" occurs when there is an issue with disk space in the system, that's why we were suggesting to free up the space 

Here is a list of possible causes:
1. Insufficient disk space: Verify available space using df -h for /output/data/chains/avail_goldberg_testnet.
2. Incorrect permissions: Check write permissions using ls -l /output/data/chains/avail_goldberg_testnet and adjust them if necessary.

Solutions:
1. Free up disk space: Delete unnecessary files or relocate the downloaded file.
2. Adjust permissions: Utilise chmod to grant appropriate write permissions if required.

Additional Notes:
1.Focus troubleshooting efforts on the /output/data/chains/avail_goldberg_testnet directory as previously suggested.
2.I did follow this step to avoid disk space issue, to monitor disk space concurrently. Open another system window and execute the "htop" command to visualise available space. Below is a screenshot demonstrating how it should appear.

![image](https://github.com/availproject/avail/assets/109763340/87963ba9-21e2-41a6-909a-af90866f5c4b)

**Comment by vinatechpro** [comment]
Exactly. The service had out of memory issue.

![6](https://github.com/availproject/avail/assets/149946061/92c4b90b-29d2-4e74-b0f5-edb79e885818)

Thanks to your guidance, I pinpointed the root cause: a hardware configuration issue arising from concurrently deploying both a full node and a light client on the same VPS.
In reality, this wouldn't have posed a problem if I had patiently waited for the full node to synchronize to the latest block before initiating the installation and execution of the light client. Following these steps, everything would have smoothly operated.

I tackled the issue as follows:
- Reinstalled the OS
- Configured and set up the Full Node
- Allowed the full node to sync to the latest block (~ 2 hours)
- Installed and start the Light Client.

The problem has been effectively resolved.

![image](https://github.com/availproject/avail/assets/149946061/d6fbfe04-f6b7-4ca3-991c-47516dbb15e1)
